import { Footer } from "@/components/principal/Footer";
import { Header } from "@/components/principal/Header";
import { CartProvider } from "@/hooks/useCart";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "MS Delivery",
    description: "Generated by create next app",
  };
  
  export default function PrincipalLayout({
    children,
  }:{
    children: React.ReactNode;
  }) {
    return (
      <>
        <CartProvider>
          <Header />
          {children}
          <Footer /> 
        </CartProvider>
      </>
    );
  }