import { HaveRestaurant } from "@/components/system/HaveRestaurant";
import { SideBar } from "@/components/system/SideBar";
import { CartProvider } from "@/hooks/useCart";
import { OrdersProvider } from "@/hooks/useOrders";
import { QueryProvider } from "@/hooks/useQuery";
import { RestaurantProvider } from "@/hooks/useRestaurant";
import { ThemeProvider } from "@/hooks/useTheme";
import { UserProvider } from "@/hooks/useUser";
import { EdgeStoreProvider } from "@/lib/edgestore";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "MS Delivery",
    description: "Generated by create next app",
  };
  
  export default function SystemLayout({
    children,
  }:{
    children: React.ReactNode;
  }) {
    
    return (
      <QueryProvider>
        <ThemeProvider>
          <CartProvider>
            <RestaurantProvider>
              <UserProvider>
                  <OrdersProvider>
                      <EdgeStoreProvider>
                        <HaveRestaurant>
                            <div className="flex">
                                <SideBar />
                                {children}
                            </div>
                        </HaveRestaurant>
                        </EdgeStoreProvider>
                  </OrdersProvider>
                </UserProvider>
            </RestaurantProvider>
          </CartProvider>
        </ThemeProvider>
      </QueryProvider>
    );
  }